apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-kubecore-app-resolver
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: resolve-kubecore-context
    functionRef:
      name: function-kubecore-app-resolver
